spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/ivenue?useSSL=false&serverTimeZone=GMT%2B8&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: "classpath*:mapper/*.xml"